MODE: 1             # 1: train, 2: test, 3: eval
NMS: 1              # 0: no non-max-suppression, 1: applies non-max-suppression on the external edges by multiplying by Canny
SEED: 10            # random seed

DEBUG: 1            # turns on debugging mode
VERBOSE: 0          # turns on verbose mode in the output console


TRAIN_GT_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/train_gt_image_fixed.txt
VAL_GT_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_gt_image_fixed.txt
TEST_GT_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_gt_image_fixed.txt

TRAIN_MASK_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/train_mask_image.txt
VAL_MASK_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_mask_threshold_image.txt
VAL_MASK2_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_mask_image.txt
TEST_MASK_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_mask_threshold_image.txt
TEST_MASK2_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_mask_image.txt

TRAIN_SHADOW_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/train_shadow_image.txt
VAL_SHADOW_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_shadow_image.txt
TEST_SHADOW_FLIST: /home/lxg/3T/data/shadow_removal/ISTD+/list/test_shadow_image.txt

LR: 0.00005                    # learning rate
D2G_LR: 0.1                   # discriminator/generator learning rate ratio
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2

INPUT_SIZE: 256               # input image size for training 0 for original size
SIGMA: 2                      # standard deviation of the Gaussian filter used in Canny edge detector (0: random, -1: no edge)
MAX_ITERS: 2e8                # maximum number of iterations to train the model

EDGE_THRESHOLD: 0.5           # edge detection threshold
L1_LOSS_WEIGHT: 1             # l1 loss weight
FM_LOSS_WEIGHT: 10            # feature-matching loss weight
STYLE_LOSS_WEIGHT: 250        # style loss weight
CONTENT_LOSS_WEIGHT: 0.1      # perceptual loss weight
INPAINT_ADV_LOSS_WEIGHT: 0.1  # adversarial loss weight

GAN_LOSS: nsgan               # nsgan | lsgan | hinge
GAN_POOL_SIZE: 0              # fake images pool size


SAMPLE_INTERVAL: 10         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 5               # number of images to sample
LOG_INTERVAL: 100000              # how many iterations to wait before logging training status (0: never)


MASK_REVERSE: 0                 # 1 reverse dunhuang, 0 no
MASK_THRESHOLD: 0               # 100 dunhuang


GPU: [0,1]            # list of gpu ids
BATCH_SIZE: 8                 # input batch size for training

SAVE_INTERVAL: 10000          # how many iterations to wait before saving model (0: never)
EVAL_INTERVAL: 500             # how many iterations to wait before model evaluation (0: never)

TRAIN_SAMPLE_INTERVAL: 1000
EVAL_SAMPLE_INTERVAL: 20


TRAIN_SAMPLE_SAVE: ./result/train
EVAL_SAMPLE_SAVE: ./result/eval
TEST_SAMPLE_SAVE: ./result/test


MODEL_LOAD: /home/lxg/server_lxg/iccv_2023/code/LIFSR/checkpoints/ISTD+.pth
